version: '2'

services:
  certbot-nginx: 
    build: .
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/etc/ssl"
      - "./fileserve:/var/www/html"
      - "./letsencrypt:/etc/letsencrypt"
      - "./cron.log:/var/log/cron.log"
    ports:
      - 80:80
      - 443:443
    network_mode: "host"