version: '2'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/etc/ssl"
      - "./fileserve:/var/www/html"
      - "./letsencrypt:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443
  certbot:
    build: ./certbot
    volumes:
      - "./letsencrypt:/etc/letsencrypt"
      - "./cron.log:/var/log/cron.log"      

#Adapted from:
#https://reprage.com/post/SSL-with-letsencrypt-nginx-and-docker
#https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg