version: '2'

services:
  certbot-nginx: 
    container_name: certbot-nginx
    build: ./certbot-nginx
    restart: unless-stopped
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./fileserve:/var/www/html"
      - "./letsencrypt:/etc/letsencrypt"
      - "./cron.log:/var/log/cron.log"
    ports:
      - 80:80
      - 443:443
    network_mode: "host"
